name: Flutter Build AppBundle

on:
  workflow_call:
    inputs:
      flutter_channel:
        required: false
        type: string
        default: "stable"
      flutter_version:
        required: false
        type: string
        default: ""
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      setup:
        required: false
        type: string
        default: ""
      working_directory:
        required: false
        type: string
        default: "."
      package_name:
        required: false
        type: string
    secrets:
      ssh_key:
        required: false
      dot_env:
        required: false
      keystore_base64:
        required: false
      key_properties:
        required: false
      playstore_account_key:
        required: false

jobs:
  build:
    name: Deveji Flutter Build
    defaults:
      run:
        working-directory: ${{inputs.working_directory}}

    runs-on: ${{inputs.runs_on}}

    # continue-on-error: true

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      - name: ğŸš€ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'    

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{inputs.flutter_version}}
          channel: ${{inputs.flutter_channel}}
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: ğŸ¤« Set SSH Key
        env:
          ssh_key: ${{secrets.ssh_key}}
        if: env.ssh_key != null
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.ssh_key}}

      - name: ğŸ“ Add .env file
        env:
          DOT_ENV: ${{ secrets.dot_env }}
        if: env.DOT_ENV != null
        run: echo "${{ secrets.dot_env }}" > .env

      - name: ğŸ” Add Android keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.keystore_base64 }}
        if: env.ANDROID_KEYSTORE != null
        id: android_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileDir: ${{inputs.working_directory}}
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.keystore_base64 }}

      - name: ğŸ” Add Android keystore properties
        env:
          ANDROID_KEYSTORE_PROPERTIES: ${{ secrets.key_properties }}
        if: env.ANDROID_KEYSTORE_PROPERTIES != null
        run: |
          echo "${{ secrets.key_properties }}" > android/key.properties

      # - name: ğŸ¤– Setup Git Config
      #   run: |
      #     git config --global user.email "github-bot@deveji.com"
      #     git config --global user.name "Deveji Bot"

      - name: ğŸ“¦ Install Dependencies
        run: |
          flutter clean
          dart run build_runner build -d
          flutter pub get

      - name: âš™ï¸ Run Setup
        if: "${{inputs.setup != ''}}"
        run: ${{inputs.setup}}

      - name: ğŸ“¦ Build AppBundle
        run: flutter build appbundle ./lib/main_production.dart --flavor production

      - name: ğŸ“¦ Upload AppBundle
        uses: actions/upload-artifact@v4
        with:
          name: appbundle
          overwrite: true
          path: "${{inputs.working_directory}}/build/app/outputs/bundle/productionRelease/app-production-release.aab"


  deploy:
    name: Deveji Flutter Deploy
    needs: build
    runs-on: ${{inputs.runs_on}}
    steps:
    - uses: actions/checkout@v4
    - name: ğŸ“¦ Get Android Build from artifacts
      uses: actions/download-artifact@v4
      with:
        name: appbundle
    - name: ğŸ“² Release Build to internal track
      uses: r0adkll/upload-google-play@v1
      env:
        PACKAGE_NAME: ${{inputs.package_name}}
        PLAYSTORE_ACCOUNT_JSON: ${{secrets.playstore_account_key}}
      if: env.PACKAGE_NAME != null && env.PLAYSTORE_ACCOUNT_JSON != null
      with:
        serviceAccountJsonPlainText: ${{ secrets.playstore_account_key }}
        packageName: ${{inputs.package_name}}
        releaseFiles: app-production-release.aab
        track: alpha
        status: completed