name: Flutter Build AppBundle

on:
  workflow_call:
    inputs:
      flutter_channel:
        required: false
        type: string
        default: "stable"
      flutter_version:
        required: false
        type: string
        default: ""
      runs_on:
        required: false
        type: string
        default: "ubuntu-latest"
      working_directory:
        required: false
        type: string
        default: "."
      flavor:
        required: false
        type: string
        default: "development"
      git_ref:
        required: false
        type: string
        default: "main"
    secrets:
      dot_env:
        required: false
      keystore_base64:
        required: false
      key_properties:
        required: false
      gh_token:
        required: true
        
jobs:
  bump-version:
    name: Deveji - Bump Version
    uses: Deveji/Deveji-Workflows/.github/workflows/flutter_bump_build.yml@main
    with:
      working_directory: ${{inputs.working_directory}}
      git_ref: ${{ github.ref }}
    secrets:
      gh_token: ${{ secrets.gh_token }}


  build:
    name: Deveji - Flutter Android Build
    needs: bump-version

    runs-on: ${{inputs.runs_on}}

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: ${{inputs.git_ref}}

      - name: ğŸš€ Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{inputs.flutter_version}}
          channel: ${{inputs.flutter_channel}}
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: ğŸ“ Add .env file
        working-directory: ${{inputs.working_directory}}
        env:
          DOT_ENV: ${{ secrets.dot_env }}
        if: env.DOT_ENV != null
        run: echo "${{ secrets.dot_env }}" > .env

      - name: ğŸ” Add Android keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.keystore_base64 }}
        if: env.ANDROID_KEYSTORE != null
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileDir: ${{inputs.working_directory}}
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.keystore_base64 }}

      - name: âš™ï¸ Add Android keystore properties
        working-directory: ${{inputs.working_directory}}
        env:
          ANDROID_KEYSTORE_PROPERTIES: ${{ secrets.key_properties }}
        if: env.ANDROID_KEYSTORE_PROPERTIES != null
        run: |
          echo "${{ secrets.key_properties }}" > android/key.properties

      - name: ğŸ“¦ Install Dependencies
        working-directory: ${{inputs.working_directory}}
        run: |
          flutter clean
          dart pub global activate build_runner
          dart run build_runner build -d
          flutter pub get

      - name: ğŸ—ï¸ Build AppBundle
        working-directory: ${{inputs.working_directory}}
        run: "flutter build appbundle ./lib/main_${{ inputs.flavor }}.dart --flavor ${{ inputs.flavor }} --release"

      - name: â˜ï¸ Upload AppBundle
        uses: actions/upload-artifact@v4.3.3
        with:
          name: appbundle
          overwrite: true
          path: "${{inputs.working_directory}}/build/app/outputs/bundle/${{ inputs.flavor }}Release/app-${{ inputs.flavor }}-release.aab"

      - name: âœš Copy AppBundle to outputs
        run: |
          mkdir -p ./outputs
          cp "${{inputs.working_directory}}/build/app/outputs/bundle/${{ inputs.flavor }}Release/app-${{ inputs.flavor }}-release.aab" ./outputs/

      - name: ğŸ—‘ï¸ Delete Previous Cache
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete outputs --confirm
        env:
          GH_TOKEN: ${{ secrets.gh_token }}

      - name: ğŸ“¦ Cache AppBundle
        uses: actions/cache/save@v4.0.2
        with:
          key: outputs
          path: "./outputs/**"